cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(famicom_hdmi C CXX ASM)
pico_sdk_init()
set(PICODVI_PATH $ENV{PICODVI_PATH})
add_subdirectory(${PICODVI_PATH}/software/libdvi libdvi)
add_executable(famicom_hdmi main.c)
target_include_directories(famicom_hdmi PRIVATE ${CMAKE_CURRENT_LIST_DIR} ${PICODVI_PATH}/software/include)
target_link_libraries(famicom_hdmi pico_stdlib hardware_pio hardware_clocks hardware_dma pico_multicore pico_util libdvi)
add_compile_definitions(PICO_PIO_USE_GPIO_BASE=1 DVI_DEFAULT_SERIAL_CONFIG=pico_sock_cfg)
pico_add_extra_outputs(famicom_hdmi)
