cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(famicom_hdmi C CXX ASM)
pico_sdk_init()
add_subdirectory(lib/libdvi libdvi)
add_executable(famicom_hdmi main.c lib/hw_config.c)
target_include_directories(famicom_hdmi PRIVATE ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/lib/libdvi/include)
target_link_libraries(famicom_hdmi pico_stdlib hardware_pio hardware_clocks hardware_dma pico_multicore libdvi)
pico_add_extra_outputs(famicom_hdmi)
