name: Build UF2
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt update && sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
      - name: Get SDK + libdvi XỊN của Waveshare
        run: |
          rm -rf pico-sdk lib build
          git clone -b 2.1.1 --depth 1 https://github.com/raspberrypi/pico-sdk.git
          git -C pico-sdk submodule update --init
          git clone --depth 1 https://github.com/ugufru/xroar-waveshare-rp2350-pizero.git tmp
          cp -r tmp/lib lib
          rm -rf tmp
      - name: Build
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
        run: |
          cmake -B build -S. -DPICO_BOARD=waveshare_rp2350_pizero -DPICO_PLATFORM=rp2350 -DPICO_COPY_TO_RAM=1 -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j1
      - uses: actions/upload-artifact@v4
        with:
          name: uf2
          path: build/*.uf2
