rm -rf pico-sdk PicoDVI build
git clone -b 2.1.1 --depth 1 https://github.com/raspberrypi/pico-sdk.git
git -C pico-sdk submodule update --init
git clone --depth 1 https://github.com/Wren6991/PicoDVI.git
git -C PicoDVI submodule update --init